version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: cptlrt-bot-wa
    restart: unless-stopped
    volumes:
      - ./finance.db:/app/finance.db
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
